import type { Client } from "pg";
import type { PgCatalog } from "./pg-stmt";
import { DsnErr, type QueryOut } from "./types";

type RelRow = {
  nspname: string;
  relname: string;
  relkind: string;
  relpersistence: string;
  comment: string | null;
  partkey: string | null;
};

type ColRow = {
  name: string;
  type: string;
  notnull: boolean;
  def: string | null;
  identity: string;
  generated: string;
};

/** 为什么: 目录命令在 Driver 内查 pg_catalog, 不 spawn pg_dump / psql. */
export async function runPgCatalog(client: Client, spec: PgCatalog): Promise<QueryOut> {
  if (spec.head === "tables") {
    return await listTables(client, spec.like);
  }
  if (spec.head === "columns") {
    return await listColumns(client, spec.rel);
  }
  return await showDdl(client, spec.rel);
}

async function listTables(client: Client, like: string | undefined): Promise<QueryOut> {
  const filters = [
    "table_type = 'BASE TABLE'",
    "table_schema NOT IN ('pg_catalog', 'information_schema')",
  ];
  const params: string[] = [];
  if (like !== undefined) {
    params.push(like);
    filters.push(`table_name LIKE $${params.length}`);
  }
  const where = filters.join(" AND ");
  const sql = `SELECT table_schema AS schema, table_name AS name
FROM information_schema.tables
WHERE ${where}
ORDER BY table_schema, table_name`;
  return await queryOut(client, sql, params);
}

async function listColumns(client: Client, rel: string): Promise<QueryOut> {
  const oid = await relOid(client, rel);
  const sql = `SELECT
  a.attname AS name,
  pg_catalog.format_type(a.atttypid, a.atttypmod) AS type,
  CASE WHEN a.attnotnull THEN 'NO' ELSE 'YES' END AS nullable,
  CASE
    WHEN a.attidentity = 'a' THEN 'generated always as identity'
    WHEN a.attidentity = 'd' THEN 'generated by default as identity'
    WHEN a.attgenerated = 's' THEN pg_catalog.pg_get_expr(ad.adbin, ad.adrelid)
    ELSE pg_catalog.pg_get_expr(ad.adbin, ad.adrelid)
  END AS default,
  CASE WHEN EXISTS (
    SELECT 1 FROM pg_catalog.pg_index i
    WHERE i.indrelid = a.attrelid AND i.indisprimary AND a.attnum = ANY (i.indkey)
  ) THEN 'PRI' ELSE '' END AS key,
  pg_catalog.col_description(a.attrelid, a.attnum) AS comment
FROM pg_catalog.pg_attribute a
LEFT JOIN pg_catalog.pg_attrdef ad
  ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
WHERE a.attrelid = $1::oid
  AND a.attnum > 0
  AND NOT a.attisdropped
ORDER BY a.attnum`;
  return await queryOut(client, sql, [oid]);
}

async function showDdl(client: Client, rel: string): Promise<QueryOut> {
  const oid = await relOid(client, rel);
  const info = await relInfo(client, oid);
  if (info.relkind === "v" || info.relkind === "m") {
    const ddl = await viewDdl(client, oid, info);
    return { columns: ["ddl"], rows: [{ ddl }] };
  }
  if (info.relkind !== "r" && info.relkind !== "p") {
    throw new DsnErr(`not a table: ${rel}`, 3);
  }
  const ddl = await tableDdl(client, oid, info);
  return { columns: ["ddl"], rows: [{ ddl }] };
}

async function relOid(client: Client, rel: string): Promise<string> {
  const res = await client.query<{ oid: string | number | null }>(
    "SELECT to_regclass($1)::oid AS oid",
    [rel],
  );
  const oid = res.rows[0]?.oid;
  if (oid === null || oid === undefined) {
    throw new DsnErr(`table not found: ${rel}`, 3);
  }
  return String(oid);
}

async function relInfo(client: Client, oid: string): Promise<RelRow> {
  const sql = `SELECT
  n.nspname,
  c.relname,
  c.relkind,
  c.relpersistence,
  pg_catalog.obj_description(c.oid, 'pg_class') AS comment,
  pg_catalog.pg_get_partkeydef(c.oid) AS partkey
FROM pg_catalog.pg_class c
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.oid = $1::oid`;
  const res = await client.query<RelRow>(sql, [oid]);
  const row = res.rows[0];
  if (row === undefined) {
    throw new DsnErr("table not found", 3);
  }
  return row;
}

async function viewDdl(client: Client, oid: string, info: RelRow): Promise<string> {
  const res = await client.query<{ def: string }>("SELECT pg_catalog.pg_get_viewdef($1::oid, true) AS def", [
    oid,
  ]);
  const def = res.rows[0]?.def;
  if (def === undefined) {
    throw new DsnErr("view definition not found", 3);
  }
  const kind = info.relkind === "m" ? "MATERIALIZED VIEW" : "VIEW";
  const qn = qualName(info.nspname, info.relname);
  const parts = [`CREATE ${kind} ${qn} AS`, def.endsWith(";") ? def : `${def};`];
  appendComment(parts, qn, info.comment);
  return parts.join("\n");
}

async function tableDdl(client: Client, oid: string, info: RelRow): Promise<string> {
  const cols = await colDefs(client, oid);
  const cons = await conDefs(client, oid);
  const idx = await indexDefs(client, oid);
  const unlogged = info.relpersistence === "u" ? "UNLOGGED " : "";
  const qn = qualName(info.nspname, info.relname);
  const body = [...cols, ...cons].map((line) => `  ${line}`).join(",\n");
  const parts = [`CREATE ${unlogged}TABLE ${qn} (\n${body}\n)`];
  if (info.partkey) {
    parts[0] = `${parts[0]} PARTITION BY ${info.partkey}`;
  }
  parts[0] = `${parts[0]};`;
  for (const def of idx) {
    parts.push(`${def};`);
  }
  appendComment(parts, qn, info.comment);
  const comments = await colComments(client, oid, qn);
  parts.push(...comments);
  return parts.join("\n");
}

async function colDefs(client: Client, oid: string): Promise<string[]> {
  const sql = `SELECT
  a.attname AS name,
  pg_catalog.format_type(a.atttypid, a.atttypmod) AS type,
  a.attnotnull AS notnull,
  pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) AS def,
  a.attidentity AS identity,
  a.attgenerated AS generated
FROM pg_catalog.pg_attribute a
LEFT JOIN pg_catalog.pg_attrdef ad
  ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
WHERE a.attrelid = $1::oid
  AND a.attnum > 0
  AND NOT a.attisdropped
ORDER BY a.attnum`;
  const res = await client.query<ColRow>(sql, [oid]);
  return res.rows.map((row) => colLine(row));
}

function colLine(row: ColRow): string {
  const bits = [quoteIdent(row.name), row.type];
  if (row.identity === "a") {
    bits.push("GENERATED ALWAYS AS IDENTITY");
  } else if (row.identity === "d") {
    bits.push("GENERATED BY DEFAULT AS IDENTITY");
  } else if (row.generated === "s" && row.def) {
    bits.push(`GENERATED ALWAYS AS (${row.def}) STORED`);
  } else if (row.def) {
    bits.push(`DEFAULT ${row.def}`);
  }
  if (row.notnull) {
    bits.push("NOT NULL");
  }
  return bits.join(" ");
}

async function conDefs(client: Client, oid: string): Promise<string[]> {
  const sql = `SELECT conname, pg_catalog.pg_get_constraintdef(oid, true) AS def
FROM pg_catalog.pg_constraint
WHERE conrelid = $1::oid
  AND contype IN ('p', 'u', 'c', 'f', 'x')
ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 WHEN 'f' THEN 3 ELSE 4 END, conname`;
  const res = await client.query<{ conname: string; def: string }>(sql, [oid]);
  return res.rows.map((row) => `CONSTRAINT ${quoteIdent(row.conname)} ${row.def}`);
}

async function indexDefs(client: Client, oid: string): Promise<string[]> {
  const sql = `SELECT pg_catalog.pg_get_indexdef(i.indexrelid, 0, true) AS def
FROM pg_catalog.pg_index i
JOIN pg_catalog.pg_class ic ON ic.oid = i.indexrelid
WHERE i.indrelid = $1::oid
  AND NOT i.indisprimary
  AND NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_constraint c
    WHERE c.conrelid = i.indrelid AND c.conindid = i.indexrelid
  )
ORDER BY ic.relname`;
  const res = await client.query<{ def: string }>(sql, [oid]);
  return res.rows.map((row) => row.def);
}

async function colComments(client: Client, oid: string, qn: string): Promise<string[]> {
  const sql = `SELECT a.attname AS name, pg_catalog.col_description(a.attrelid, a.attnum) AS comment
FROM pg_catalog.pg_attribute a
WHERE a.attrelid = $1::oid
  AND a.attnum > 0
  AND NOT a.attisdropped
  AND pg_catalog.col_description(a.attrelid, a.attnum) IS NOT NULL
ORDER BY a.attnum`;
  const res = await client.query<{ name: string; comment: string }>(sql, [oid]);
  return res.rows.map((row) => {
    const col = `${qn}.${quoteIdent(row.name)}`;
    return `COMMENT ON COLUMN ${col} IS ${sqlString(row.comment)};`;
  });
}

function appendComment(parts: string[], qn: string, comment: string | null): void {
  if (comment) {
    parts.push(`COMMENT ON TABLE ${qn} IS ${sqlString(comment)};`);
  }
}

function qualName(schema: string, name: string): string {
  return `${quoteIdent(schema)}.${quoteIdent(name)}`;
}

function quoteIdent(name: string): string {
  if (/^[a-z_][a-z0-9_]*$/.test(name)) {
    return name;
  }
  return `"${name.replaceAll('"', '""')}"`;
}

function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

async function queryOut(client: Client, sql: string, params: unknown[]): Promise<QueryOut> {
  const res = await client.query(sql, params);
  if (Array.isArray(res)) {
    throw new DsnErr("multiple result sets", 3);
  }
  return {
    columns: res.fields.map((field) => field.name),
    rows: res.rows.map((row) => ({ ...(row as Record<string, unknown>) })),
  };
}
